name = "contextjson"
compatibility_date = "2025-05-09"
dev.port = 3000
assets.directory = "./"
main = "contextjson-uithub.ts"
routes = [
  { pattern = "contextjson.com", custom_domain = true },
  { pattern = "www.contextjson.com", custom_domain = true }
]


[[kv_namespaces]]
binding = "CONTEXTS_KV"
id = "1e9d3b08abc842b787bd61b79ed30ab1"